version: '3'
services:
  flask-app:
    build:
      context: ./api
    image: shayawn/devops-assessment-app-api
    ports:
      - "5002:5002"
    environment:
      - WELCOME='backend message'

  react-app:
    build:
      context: ./frontend
    image: shayawn/devops-assessment-app-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_WELCOME='frontend message'
      - REACT_APP_API_URL=http://localhost:5002/api
