version: '3'
services:
  flask-app:
    image: shayawn/devops-assessment-app-api
    ports:
      - "5000:5002"
    environment:
      - WELCOME='backend message'

  react-app:
    image: shayawn/devops-assessment-app-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_WELCOME='frontend message'
      - REACT_APP_API_URL=http://localhost:5002/api
